version: 0.2.{build}

image:
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive
  - cd scripts
  - EmbedResources.bat
  - UpdateVersion.bat
  - build.bat vs2017

build:
  project: .projects/vs2017/Texeled.sln

artifacts:
  - path: .out\*.exe
