version: 0.1.{build}

image:
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive
  - cd scripts
  - EmbedResources.bat
  - "build 2017.bat"

build:
  project: .projects/vs2017/Texeled.sln

artifacts:
  - path: .out\*.exe
